export const movementCategories = [
  { id: "strength", label: "Krachttraining", icon: "🏋️" },
  { id: "cardio", label: "Cardio", icon: "🚴" },
  { id: "mobility", label: "Mobiliteit / herstel", icon: "🧘" },
];

export const starterMovementItems = [
  {
    id: "movement-borst",
    name: "Borsttraining",
    category: "strength",
    subCategory: "Borst",
    muscleGroup: "Borst",
    defaultSets: "",
    defaultReps: "",
    intensity: "",
    defaultDurationMinutes: 75,
    note: "Krachttraining borst.",
    active: true,
  },
  {
    id: "movement-schouders",
    name: "Schoudertraining",
    category: "strength",
    subCategory: "Schouders",
    muscleGroup: "Schouders",

    defaultSets: "",
    defaultReps: "",

    intensity: "",
    defaultDurationMinutes: 75,
    note: "Krachttraining schouders.",
    active: true,
  },
  {
    id: "movement-benen",
    name: "Benentraining",
    category: "strength",
    subCategory: "Benen",
    muscleGroup: "Benen",
    defaultSets: "",
    defaultReps: "",
    intensity: "",
    defaultDurationMinutes: 75,
    note: "Krachttraining benen.",
    active: true,
  },
  {
    id: "movement-wandelen",
    name: "Wandelen",
    category: "cardio",
    subCategory: "Rustig",
    muscleGroup: "",
    defaultSets: "",
    defaultReps: "",
    defaultDurationMinutes: 30,
    intensity: "Laag",
    note: "Lage intensiteit.",
    active: true,
  },
  {
    id: "movement-fietsen",
    name: "Fietsen",
    category: "cardio",
    subCategory: "Gemengd",
    muscleGroup: "",
    defaultDurationMinutes: 45,
    note: "Cardio / vervoer.",
    active: true,
  },
];
